version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
        build:
          working_directory: ~/lelik01/Akarin
          parallelism: 1
          shell: /bin/bash --login
          environment:
            CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
            CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
        docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
          command: /sbin/init
        steps:
        # Machine Setup
        - checkout
        # Prepare for artifact
        - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        - run:
            working_directory: ~/Akarin-project/Akarin
            command: sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java; sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac; echo -e "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $BASH_ENV
        # Dependencies
        # Restore the dependency cache
        - restore_cache:
            keys:
            # This branch if available
            - v1-dep-{{ .Branch }}-
            # Default branch if not
            - v1-dep-ver/1.12.2-
            # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
            - v1-dep-
        - run: git config --global user.email "circle@circleci.com"
        - run: git config --global user.name "CircleCI"
        - run: chmod +x scripts/inst.sh
        - run: ./scripts/inst.sh --setup --remote
        # Save dependency cache
        - save_cache:
            key: v1-dep-{{ .Branch }}-{{ epoch }}
            paths:
            - ~/.m2
        # Test
        - run: yes|cp -rf ./akarin-*.jar $CIRCLE_ARTIFACTS
        # Teardown
        # Save test results
        - store_test_results:
            path: /tmp/circleci-test-results
        # Save artifacts
        - store_artifacts:
            path: /tmp/circleci-artifacts
        - store_artifacts:
            path: /tmp/circleci-test-results
